config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :subcats do
      resources :products
    end
  end

  root to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcats, dependent: :destroy
  has_many :products, through: :subcats
  
  validates :name, uniqueness: true
  
  mount_uploader :csv, CSVUploader
  
  before_save :import_csv
  
  def import_csv
    if self.csv.present?
      filename = Rails.root + self.csv.current_path
      options = {:key_mapping => { :downcase_header => true }}
      SmarterCSV.process(filename, options) do |hash|
        hash.each do |h|
         Category.create(name: h[:name])
         
         c = Category.where(name: h[:name.downcase]).first
         c.subcats.create(subcat_name: h[:subcat_name], subcat_id: h[:subcat_id])
         sleep 0.1
         s = Subcat.where(subcat_name: h[:subcat_name.downcase]).first
         s.products.create(manuf_id: h[:manuf_id], manuf_description: h[:manuf_description], gage: h[:gage], price: h[:price], weight: h[:weight], length: h[:length], finish: h[:finish])
        end
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcat
  has_one :category, through: :subcat

  validates :manuf_id, uniqueness: true

end

app/models/subcat.rb
class Subcat < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy
  
  validates :subcat_name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :csv)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @subcat = Subcat.find(params[:subcat_id])
    @products = @subcat.products.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @subcat = Subcat.find(params[:subcat_id])
    @product = @subcat.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @subcat = Subcat.find(params[:subcat_id])
    @product = @subcat.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to category_subcat_product_path(@subcat.category, @subcat, @product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to category_subcat_product_path(@subcat.category, @subcat, @product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to category_subcat_path(@subcat.category, @subcat), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @subcat = Subcat.find(params[:subcat_id])
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:manuf_id, :manuf_description, :subcat_id, :price, :gage, :weight, :length, :finish)
    end
end

app/controllers/subcats_controller.rb
class SubcatsController < ApplicationController
  before_action :set_subcat, only: [:show, :edit, :update, :destroy]

  # GET /subcats
  # GET /subcats.json
  def index
    @subcats = Category.find(params[:category_id]).subcats.all
  end

  # GET /subcats/1
  # GET /subcats/1.json
  def show
  end

  # GET /subcats/new
  def new
    @category = Category.find(params[:category_id])
    @subcat = @category.subcats.build
  end

  # GET /subcats/1/edit
  def edit
  end

  # POST /subcats
  # POST /subcats.json
  def create
    @category = Category.find(params[:category_id])
    @subcat = @category.subcats.build(subcat_params)

    respond_to do |format|
      if @subcat.save
        format.html { redirect_to category_subcat_path(params[:category_id], @subcat.id), notice: 'Subcat was successfully created.' }
        format.json { render :show, status: :created, location: @subcat }
      else
        format.html { render :new }
        format.json { render json: @subcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcats/1
  # PATCH/PUT /subcats/1.json
  def update
    respond_to do |format|
      if @subcat.update(subcat_params)
        format.html { redirect_to category_subcat_path(@subcat.category, @subcat.id), notice: 'Subcat was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcat }
      else
        format.html { render :edit }
        format.json { render json: @subcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcats/1
  # DELETE /subcats/1.json
  def destroy
    @subcat.destroy
    respond_to do |format|
      format.html { redirect_to @subcat.category, notice: 'Subcat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcat
      @subcat = Subcat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcat_params
      params.require(:subcat).permit(:subcat_name, :category_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subcats_helper.rb
module SubcatsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :csv, 'Import CSV File' %>
    <%= form.file_field :csv %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<%= link_to 'New Sub Category', new_category_subcat_path(@category) %> | 
<%= link_to 'Sub Categories', category_subcats_path(@category) %> | 
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Products" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Products" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
			 <div class="text-center">
				 <%= yield %>
			 </div>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product, url: @product.new_record? ? category_subcat_products_path(@subcat.category, @subcat) : category_subcat_product_path(@subcat.category, @subcat) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :manuf_id %>
    <%= form.text_field :manuf_id %>
  </div>

  <div class="field">
    <%= form.label :manuf_description %>
    <%= form.text_field :manuf_description %>
  </div>

  <div class="field">
    <%= form.label :gage %>
    <%= form.text_field :gage %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length %>
  </div>

  <div class="field">
    <%= form.label :finish %>
    <%= form.text_field :finish %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', category_subcat_product_path(@subcat.category, @subcat, @product) %> |
<%= link_to 'Back', category_subcat_products_path(@subcat) %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Subcat</th>
			<th>Manuf</th>
      <th>Manuf description</th>
			<th>Gage</th>
      <th>Price</th>
      <th>Weight</th>
      <th>Length</th>
      <th>Finish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.subcat.subcat_name, category_subcat_path(product.subcat.category, product.subcat) %></td>
				<td><%= product.manuf_id %></td>
				<td><%= product.manuf_description %></td>
        <td><%= product.gage %></td>
				<td><%= product.price %></td>
				<td><%= product.weight %></td>
				<td><%= product.length %></td>
				<td><%= product.finish %></td>
				
        <td><%= link_to 'Show', category_subcat_product_path(product.subcat.category, product.subcat, product) %></td>
        <td><%= link_to 'Edit', edit_category_subcat_product_path(product.subcat.category, product.subcat, product) %></td>
        <td><%= link_to 'Destroy', category_subcat_product_path(product.subcat.category, product.subcat, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_category_subcat_product_path(params[:category_id], params[:subcat_id]) %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', category_subcat_products_path(@subcat.category, @subcat) %>

app/views/products/show.html.erb
<p>
  <strong>Manuf:</strong>
  <%= @product.manuf_id %>
</p>

<p>
  <strong>Manuf description:</strong>
  <%= @product.manuf_description %>
</p>

<p>
  <strong>Gage:</strong>
  <%= @product.gage %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>

<p>
  <strong>Length:</strong>
  <%= @product.length %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @product.finish %>
</p>

<p>
  <strong>Subcat:</strong>
  <%= link_to @product.subcat.subcat_name, category_subcat_path(@product.subcat.category, @product.subcat) %>
</p>

<%= link_to 'Edit', edit_category_subcat_product_path(@product.subcat.category, @product.subcat, @product) %> |
<%= link_to 'Back', category_subcat_path(@product.subcat.category, @product.subcat) %>

app/views/subcats/_form.html.erb
<%= simple_form_for @subcat, url: @subcat.new_record? ? category_subcats_path(@subcat.category) : category_subcat_path(@subcat.category) do |form| %>
  <% if @subcat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcat.errors.count, "error") %> prohibited this subcat from being saved:</h2>

      <ul>
      <% @subcat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subcat_name %>
    <%= form.text_field :subcat_name, value: @subcat.subcat_name or nil %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

app/views/subcats/edit.html.erb
<h1>Editing Subcat</h1>

<%= render 'form', subcat: @subcat %>

<%= link_to 'Show', category_subcat_path(params[:category_id], @subcat) %> |
<%= link_to 'Back', category_subcats_path(params[:category_id]) %>

app/views/subcats/index.html.erb
<h1>Subcats</h1>

<table>
  <thead>
    <tr>
      <th>Subcat name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcats.each do |subcat| %>
      <tr>
        <td><%= subcat.subcat_name %></td>
        <td><%= link_to subcat.category.name, category_path(params[:category_id]) %></td>
        <td><%= link_to 'Show', category_subcat_path(params[:category_id], subcat.id) %></td>
        <td><%= link_to 'Edit', edit_category_subcat_path(params[:category_id], subcat.id) %></td>
        <td><%= link_to 'Destroy', category_subcat_path(params[:category_id], subcat.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcat', new_category_subcat_path(params[:category_id]) %>

app/views/subcats/new.html.erb
<h1>New Subcat</h1>

<%= render 'form', subcat: @subcat %>

<%= link_to 'Back', category_path(params[:category_id]) %>

app/views/subcats/show.html.erb
<p>
  <strong>Subcat name:</strong>
  <%= @subcat.subcat_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to @subcat.category.name, category_path(@subcat.category) %>
</p>
<%= link_to 'New Product', new_category_subcat_product_path(params[:category_id], @subcat) %> | 
<%= link_to 'Products', category_subcat_products_path(params[:category_id], @subcat) %> | 
<%= link_to 'Edit', edit_category_subcat_path(params[:category_id], @subcat) %> |
<%= link_to 'Back', category_subcats_path(params[:category_id]) %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>

<h5><%= link_to 'New Category', new_category_path %></h5>